version: '3.4'

services:
  one-api:
    image: connermo/one-api:latest
    container_name: one-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - SQL_DSN=sqlite:/data/one-api.db
      - SESSION_SECRET=random_string
      - TZ=Asia/Shanghai
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3