name: Linux Release (Offline)
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'
      - '!*-alpha*'
      - '!*-preview*'
  workflow_dispatch:
    inputs:
      name:
        description: 'reason'
        required: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check repository URL
        run: |
          REPO_URL=$(git config --get remote.origin.url)
          if [[ $REPO_URL == *"pro" ]]; then
            exit 1
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Frontend
        env:
          CI: ""
        run: |
          cd web
          git describe --tags > VERSION
          chmod u+x ./build.sh && ./build.sh
          cd ..
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Download tiktoken cache
        run: |
          mkdir -p tiktoken_cache
          cd tiktoken_cache
          BASE_URL="https://openaipublic.blob.core.windows.net/encodings"
          FILES="r50k_base.tiktoken p50k_base.tiktoken cl100k_base.tiktoken o200k_base.tiktoken"
          for file in $FILES; do
            echo "Downloading $file..."
            curl -L -o "$file" "$BASE_URL/$file"
          done
          cd ..
      - name: Build Backend (Offline)
        env:
          TIKTOKEN_CACHE_DIR: ./tiktoken_cache
          DATA_GYM_CACHE_DIR: ./tiktoken_cache
        run: |
          go mod download
          go build -ldflags "-s -w -X 'github.com/connermo/one-api/common.Version=$(git describe --tags)' -extldflags '-static'" -o one-api-offline

      - name: Create offline package
        run: |
          mkdir -p one-api-offline-package
          cp one-api-offline one-api-offline-package/
          cp -r tiktoken_cache one-api-offline-package/
          tar -czf one-api-offline-linux-amd64.tar.gz -C one-api-offline-package .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            one-api-offline-linux-amd64.tar.gz
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}